### ISSUE TITLE
Package License?

### ISSUE THREAD

**Issue by phue** [Jhsmit/ipymolstar#17]
Thanks for this package!
It works like a breeze with py-shiny as well and I'd love to use this for the AlphaFold frontend at our institution.
Would you mind adding a license to the repo?

**Comment by Jhsmit** [comment]
Hi, didnt realize i forgot to add that, thanks for letting me know. 

Which functionality are you using? are you using any of the methods like `color`, `focus`, `set_color`, `update`, etc?
I'm considering removing those in a refactoring.

**Comment by phue** [comment]
Thanks alot!
No currently I'm not using any of these, just [this](https://gitlab.rlp.net/imbforge/fold2go/-/blob/next/modules/shiny/resources/usr/bin/app.py?ref_type=heads#L166-171).
I was planning to implement coloring by b-factor though, but I saw that mol* core has built-in support for this as of `v4.4.1`

Is there anything that could break if you bump to `pdbe-molstar=3.3.2` (which would pull in mol* core `4.8.0`)?

**Comment by Jhsmit** [comment]
You can already use `alphafold_view` to use alphafold colors

See a pycafe example [here](https://py.cafe/snippet/solara/v1?pycafe-app-view#c=H4sIAEnRTWcEA41W227cNhD9lcXmISlgyZL2ZhvQQ9MiSB8KtEWBPsRBQFHcFb0SSZOUbSXwv_fMaK3dTQIkcBAsZ4YzZ85cqC9zaWs1v5lvve1m2g2dbUMUfqY7Z32c_fX7W_XnKLo1t0b2IdruUy2imJWzWsv4pvdt-bqJ0YWby0vRukZsbVunqtKpkGm_v9zqVoXLX98lf1_9sXi_Sd7lSYeY7aeHZSr19vXFbGt9J2L5ejxV2gg_lO9EG9Qvt8aJnUKsEyBvTlCUJ78vZo3SuwaOVlnmnuBqgvPpQavH8l_fk0f6m1_MvbrvtVedMjGAgGPu0MXBESnBtsILnN0QG2sgcYOtda2ShywtVmkOVSsG28f5zZf5g_JBk1UB59bGf-wjiQ--PE4Xc9notvYKRh8mTRRVUBHKR13HZn6Tr7KLeafNf-NxMZ7ec27jUde4Rry-hdeg_G_WRKGNIujfi0CmSTXawsQJ8jufP398vphsJhTfcwDl8Z5wLnXD_PzuUX3Kaxqf4nmYn6Dhx6kfUvlR2i8ZnwGYwozNAro3q5-JGZWHWLQ_CvpiR1Hp7_mC6UeLffiIbrFyT0fyAoJg_2rWiNDczGS1XF6vs_VmVV9V9fJarLdVlhdSbousWObFrRFm0LYsl-k6LVJnQ8xZhq7ZqViWWXqd5guI_M6aIpHbrS7LYpHmaXYmTDBgtTa7AG0OT9ns1awDLDICYWWZpwu-EmK0e2VghzNLYvR06-CzEnIvRdtSaLiBQIk-6m3fBtu7JSHNixTAq1YJ2ZTlenQjcVDRYtjKcoVYSEMqj4uEN4P3TVrg1phAnuaYM5wa4VG3xNCuaPVn5QnWgtzLVst9WV4B1QYn23UjIqhqVfU7N5AbqKdEayWtF9HCB5yT-1pt-6Dqp46z2ZBIPSmJdMwOqMaEt6DkLlgTgL8TJAaBsKSCUmEJUb5myX1tKChDb_KcnOZL8tH0nTCAz-ywV10b-FqkS_x0w155owACNV5RBse1RD5QYxbRNiopY452ECQ7ZQCYaD0UBIqHHqGAEpV-OYNpZiTnakA2dhCuEYUriIKte_CDZUYVOeC8UzXqgdM1n7S5EwVnTJ6JFmc1mprrwp5PqUKymxTNedcDq_IJaob2p4jrM7H1gLuiDjgK1QOtEgp9ZovJxsbl4iDcVNtzdYKfPI58H902GbSiStyw4zVFOu75E91ECmVDc9UJv6_tIyhBhx6PiY7wMyVN4t4FsUUe1DZ8MbrWxlZXiTYtVgeF417tQDM3HHPY6RB70pIrnE0lWxGCllyskxRJMdKHm_jHEmuQLkTo3TX1kqkOzyq1eMYSFWIiwmAkrZEcbAKvsVFV1qJ316DnJMZBnoRGH-aJXPTdOE0Fx7AI6fEcgqUNagZ3TpjaSgwEWIT0MAFO-ICQGYYQfDj15JQEsCU21jGiwxRjT2LOmaANdaLTbcsrCdyy-1ZESqvW5H2Joq0hxKeLio3qw9RWgMs9SyoXE1o2ew05Mbu8gjzQoBA11-nVEUEYdmgVuo6WJ9zY6d5KFRCMEJHH3it05GhVcDqDpPwUt2JBt6auQgPwgGKGuVXUE5Y-fSNAR4VDkd3hg4K-oEaXbI8viUAPBIkwcByGZxwfOmrEXoBNdsByGraktbvdiANoSTUIWmi0d9nr5-4eSuyhE9o9dnO06Op8rA4932gURr9gEv1WLhaL6wRJa4S3CAB_VH_SXF-tv9YgltcSCz9fgF-yw4lqQyuSwqCy3tWB5wYXrk7gBGXqIno8iRMirP3eHd6LNa0oZB30E-lBLwAGo_FWcE9jHeHMn218RMFfztPC-Erc8yvzIsLsaiwcyh47C5KIV45Yh7_DAqJl3KoYuU0XvGjR7bRlam5y5IOLeDkGGQJWJKhiG-tHCx4dpKgjvCAnjAg6GSJ8QBAn39QZU5LyR0CWjWZ4lM56aYneRMjea-y7joYE2JAThcWGweZZkB-uZv-gsWVRb8aOW48iyqa2eObOG4Pl9LQhAOLj8lElsR0jKsT9CkyPCguotTSUaK9xeCBTeI0Pnxq0fEdhgAs85C-jSkUGrEkBW9BBpuMCxlfFS6YjQooXQov_7lsdFU7z5_8BhJeWu8cMAAA)

I'll update ipymolstar, but if you want to use custom colors based off b factor value you probably have to provide the colors externally through `color_data` (which i might rename because it does other things now except for coloring)
